from config import llm

from prompts.planning_prompt import PLANNING_PROMPT

from scheduler.study_slots import extract_study_slots

from utils.mode_prompt import get_mode_instruction
from datetime import datetime
import json

today = datetime.today().strftime("%d %B %Y")

from utils.prompt_formatter import (
    format_timetable,
    format_tasks,
    format_slots,
)


def planning_agent(state):

    print("\n========== Planning Agent ==========")

    # Get planning instructions based on selected mode
    mode_instruction = get_mode_instruction(state["mode"])

    # Extract available study slots
    slots = extract_study_slots(state["timetable"])

    # Convert Python objects into readable text
    timetable_text = format_timetable(state["timetable"])

    slots_text = format_slots(slots)

    tasks_text = format_tasks(
        state["assignments"] + state["classroom_tasks"]
    )

    # Build the prompt
    prompt = PLANNING_PROMPT.format(
        today=today,
        mode_instruction=mode_instruction,
        timetable=timetable_text,
        slots=slots_text,
        tasks=tasks_text,
    )

    # (Optional) Print prompt for debugging
    print("\n========== PROMPT SENT TO QWEN ==========\n")
    print(prompt)

    # Generate study plan
    response = llm.invoke(prompt)

    study_plan = json.loads(response.content)
    study_plan["mode"] = state["mode"]
    task_lookup = {
    (task.subject, task.work): task.days_remaining
    for task in state["assignments"] + state["classroom_tasks"]
}

# Overwrite days_remaining with Python's accurate value
    for item in study_plan["plan"]:

        key = (item["subject"], item["work"])

        if key in task_lookup:
            item["days_remaining"] = task_lookup[key]


    state["study_plan"] = study_plan

    print("Study plan generated by Qwen.")

    return state